### Agenda:

* filter the data from DataFrame
* value_counts function
* unique function

In [101]:
import pandas as pd

In [102]:
from pathlib import Path

In [103]:
fileName=Path('data/MFG10YearTerminationData.csv')

In [104]:
df = pd.read_csv(fileName)

In [105]:
df

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49648,8258,12/1/2015 0:00,5/28/1994,8/19/2013,12/30/2015,21,2,Valemount,Dairy,Dairy Person,34,M,Male,Layoff,Involuntary,2015,TERMINATED,STORES
49649,8264,8/1/2013 0:00,6/13/1994,8/27/2013,8/30/2013,19,0,Vancouver,Customer Service,Cashier,44,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49650,8279,12/1/2015 0:00,7/18/1994,9/15/2013,12/30/2015,21,2,White Rock,Customer Service,Cashier,39,F,Female,Layoff,Involuntary,2015,TERMINATED,STORES
49651,8296,12/1/2013 0:00,9/2/1994,10/9/2013,12/31/2013,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49652,8321,12/1/2014 0:00,11/28/1994,11/24/2013,12/30/2014,20,1,Grand Forks,Customer Service,Cashier,13,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [106]:
df["city_name"].value_counts()

Vancouver           11211
Victoria             4885
Nanaimo              3876
New Westminster      3211
Kelowna              2513
Burnaby              2067
Kamloops             2061
Prince George        2048
Cranbrook            1785
Surrey               1560
Richmond             1401
Terrace              1228
Chilliwack           1167
Trail                 925
Langley               901
Vernon                898
Squamish              806
Quesnel               703
Abbotsford            681
North Vancouver       648
Fort St John          621
Williams Lake         617
West Vancouver        613
Port Coquitlam        545
Aldergrove            520
Fort Nelson           322
Nelson                317
New Westminister      254
Grand Forks           236
White Rock            231
Haney                 182
Princeton             136
Dawson Creek          129
Bella Bella           126
Ocean Falls            65
Pitt Meadows           57
Cortes Island          43
Valemount              37
Dease Lake             18
Blue River              9
Name: city_name, dtype: int64

In [110]:
df[( df["city_name"] == "Blue River" ) | ( df["city_name"] == "Dease Lake" ) ]

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
10644,3169,12/31/2006 0:00,12/20/1958,12/2/1994,12/30/2014,48,12,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,STORES
10645,3169,12/31/2007 0:00,12/20/1958,12/2/1994,12/30/2014,49,13,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,STORES
10646,3169,12/31/2008 0:00,12/20/1958,12/2/1994,12/30/2014,50,14,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,STORES
10647,3169,12/31/2009 0:00,12/20/1958,12/2/1994,12/30/2014,51,15,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,STORES
10648,3169,12/31/2010 0:00,12/20/1958,12/2/1994,12/30/2014,52,16,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,STORES
10649,3169,12/31/2011 0:00,12/20/1958,12/2/1994,12/30/2014,53,17,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2011,ACTIVE,STORES
10650,3169,12/31/2012 0:00,12/20/1958,12/2/1994,12/30/2014,54,18,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2012,ACTIVE,STORES
10651,3169,12/31/2013 0:00,12/20/1958,12/2/1994,12/30/2014,55,19,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2013,ACTIVE,STORES
25653,5236,12/31/2006 0:00,6/12/1970,12/23/2000,12/30/2014,36,6,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,STORES
25654,5236,12/31/2007 0:00,6/12/1970,12/23/2000,12/30/2014,37,7,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,STORES
25655,5236,12/31/2008 0:00,6/12/1970,12/23/2000,12/30/2014,38,8,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,STORES
25656,5236,12/31/2009 0:00,6/12/1970,12/23/2000,12/30/2014,39,9,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,STORES
25657,5236,12/31/2010 0:00,6/12/1970,12/23/2000,12/30/2014,40,10,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,STORES
25658,5236,12/31/2011 0:00,6/12/1970,12/23/2000,12/30/2014,41,11,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2011,ACTIVE,STORES
25659,5236,12/31/2012 0:00,6/12/1970,12/23/2000,12/30/2014,42,12,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2012,ACTIVE,STORES
25660,5236,12/31/2013 0:00,6/12/1970,12/23/2000,12/30/2014,43,13,Dease Lake,Dairy,Dairy Person,10,M,Male,Not Applicable,Not Applicable,2013,ACTIVE,STORES
26133,5288,12/31/2006 0:00,12/27/1970,4/7/2001,12/30/2014,36,5,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2006,ACTIVE,STORES
26134,5288,12/31/2007 0:00,12/27/1970,4/7/2001,12/30/2014,37,6,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2007,ACTIVE,STORES
26135,5288,12/31/2008 0:00,12/27/1970,4/7/2001,12/30/2014,38,7,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2008,ACTIVE,STORES
26136,5288,12/31/2009 0:00,12/27/1970,4/7/2001,12/30/2014,39,8,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2009,ACTIVE,STORES
26137,5288,12/31/2010 0:00,12/27/1970,4/7/2001,12/30/2014,40,9,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2010,ACTIVE,STORES
26138,5288,12/31/2011 0:00,12/27/1970,4/7/2001,12/30/2014,41,10,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2011,ACTIVE,STORES
26139,5288,12/31/2012 0:00,12/27/1970,4/7/2001,12/30/2014,42,11,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2012,ACTIVE,STORES
26140,5288,12/31/2013 0:00,12/27/1970,4/7/2001,12/30/2014,43,12,Blue River,Dairy,Dairy Person,4,F,Female,Not Applicable,Not Applicable,2013,ACTIVE,STORES
48616,3169,12/1/2014 0:00,12/20/1958,12/2/1994,12/30/2014,56,20,Dease Lake,Dairy,Dairy Person,10,M,Male,Layoff,Involuntary,2014,TERMINATED,STORES
49200,5236,12/1/2014 0:00,6/12/1970,12/23/2000,12/30/2014,44,14,Dease Lake,Dairy,Dairy Person,10,M,Male,Layoff,Involuntary,2014,TERMINATED,STORES
49206,5288,12/1/2014 0:00,12/27/1970,4/7/2001,12/30/2014,44,13,Blue River,Dairy,Dairy Person,4,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [117]:
df["city_name"].unique()

array(['Vancouver', 'Terrace', 'Nanaimo', 'Nelson', 'Kelowna', 'Victoria',
       'Kamloops', 'Fort St John', 'Surrey', 'Vernon', 'Quesnel',
       'Chilliwack', 'Dawson Creek', 'Squamish', 'New Westminster',
       'Port Coquitlam', 'Cortes Island', 'Burnaby', 'Bella Bella',
       'Cranbrook', 'Williams Lake', 'Trail', 'Prince George', 'Richmond',
       'Grand Forks', 'West Vancouver', 'Abbotsford', 'Aldergrove',
       'Langley', 'North Vancouver', 'White Rock', 'New Westminister',
       'Fort Nelson', 'Haney', 'Valemount', 'Ocean Falls', 'Princeton',
       'Dease Lake', 'Pitt Meadows', 'Blue River'], dtype=object)